version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      shared-workflows:
        patterns:
          - "esphome/workflows*"
