packages:
  core: !include a5t.yaml
  provisioning: !include ../../packages/provisioning.yaml
  push_updates: !include ../../packages/push-updates.yaml

esphome:
  project:
    name: "Nous.A5T"
    version: dev
